Reservierung implementieren
DACHPC/reservation-tool pull request #5
Opened 2024-10-21 07:34 UTC by NoahKoe

2024-10-21 10:38 UTC, pe42iqoq requested changes
Bitte Tests für konkrete Klassen schreiben und dann die entsprechenden Klassen Implementieren.

2024-10-23 09:16 UTC, pe42iqoq requested changes

2024-10-23 09:17 UTC, pe42iqoq requested changes

2024-10-23 09:17 UTC, pe42iqoq commented on backend/src/main/java/com/dach/reservation_tool/Reservation.java
Sollte eine Reservation nicht auch ein Reservable besitzen?

2024-10-23 09:18 UTC, pe42iqoq commented on backend/src/test/java/com/dach/reservation_tool/ReservationTest.java
Ich würde hier auch noch nach Reservables testen.

2024-10-23 10:48 UTC, NoahKoe commented on backend/src/test/java/com/dach/reservation_tool/ReservationTest.java
> +    void testIdSetterAndGetter() {
Done

2024-10-23 10:48 UTC, NoahKoe commented on backend/src/test/java/com/dach/reservation_tool/ReservationTest.java
> +    void testEqualsAndHashCode() {
Done

2024-10-23 10:51 UTC, NoahKoe commented on backend/src/test/java/com/dach/reservation_tool/ConferenceRoomTest.java
Ja die Klasse wollte ich eigentlich nicht pushen. Mir ist aufgefallen, dass ConferenceRooms ja jetzt im Enum umgesetzt sind. Es gibt hier also keine Klasse, die man testen könnte

2024-10-23 10:55 UTC, NoahKoe commented on backend/src/main/java/com/dach/reservation_tool/Reservation.java
Ja und noch einiges mehr. Im Ticket steht nur was vom Reservable. Das hab ich jetzt eingefügt. Haben wir irgendwo noch festgehalten, was da sonst noch alles drin sein soll? Falls nein würde ich die Klärung und Umsetzung dessen als Ticket in den nächsten Sprint oder ins Backlog legen

2024-10-23 11:01 UTC, NoahKoe commented on backend/src/test/java/com/dach/reservation_tool/ReservationTest.java
> +    void testIdSetterAndGetter() {
Ich kann den Test splitten, aber es gibt hier nur einen Assert. Ich bin mir nicht sicher, dass das sinnvoll wäre. Oder stellst du dir die Tests anders vor?

2024-10-23 11:06 UTC, pe42iqoq commented on backend/src/test/java/com/dach/reservation_tool/ReservationTest.java
> +    void testIdSetterAndGetter() {
Du müsstest dann die entsprechenden Klassen mocken. (Fun fact: in nem echten Projekt würde man wahrscheinlich eh keine Getter und Setter testen, aber ist ne gute Übung und das Prinzip lässt sich am Ende auch auf andere Methoden übertragen)

2024-10-23 11:09 UTC, NoahKoe commented on backend/src/test/java/com/dach/reservation_tool/ReservationTest.java
> +    void testIdSetterAndGetter() {
Wenn die Tests eh unnötig, sind würde ich mocken jetzt nicht nochmal üben. Hab ich bei Filmpicker ja schon gemacht. Ich hätte das Ticket nur gerne bis zum Sprintende fertig.

2024-10-23 11:12 UTC, pe42iqoq commented on backend/src/test/java/com/dach/reservation_tool/ReservationTest.java
> +    void testIdSetterAndGetter() {
As you wish, dann bitte die Tests komplett entfernen.

2024-10-23 12:58 UTC, NoahKoe commented on backend/src/test/java/com/dach/reservation_tool/ReservationTest.java
> +    void testIdSetterAndGetter() {
Done

2024-10-23 13:03 UTC, pe42iqoq commented on backend/src/main/java/com/dach/reservation_tool/Reservation.java
Haben wir nur im Groben besprochen. Das wird sich dann in der Zukunft herauskristallisieren. Aber keine Sorge, wenn es mal ein wirklich deutlich größerer Aufwand werden sollte, dann macht es auf jeden Fall Sinn sich da nochmal zu synchen.

2024-10-23 13:11 UTC, pe42iqoq approved these changes

2024-10-23 13:13 UTC, ngnvhnm approved these changes

2024-10-23 13:29 UTC, merged